steps:
    - name: gcr.io/cloud-builders/docker
      args:
          - "build"
          - "-t"
          - "asia-southeast2-docker.pkg.dev/$PROJECT_ID/jalanku-artifact/data-vis:$COMMIT_SHA"
          - "."
    - name: gcr.io/cloud-builders/docker
      args:
          - "push"
          - "asia-southeast2-docker.pkg.dev/$PROJECT_ID/jalanku-artifact/data-vis:$COMMIT_SHA"
    - name: "gcr.io/cloud-builders/gcloud"
      entrypoint: gcloud
      args:
          - "run"
          - "deploy"
          - "model-vis"
          - "--image=asia-southeast2-docker.pkg.dev/$PROJECT_ID/jalanku-artifact/data-vis:$COMMIT_SHA"
          - "--region=asia-southeast2"
          - "--cpu=1"
          - "--memory=512Mi"
          - "--allow-unauthenticated"
images:
    - "asia-southeast2-docker.pkg.dev/$PROJECT_ID/jalanku-artifact/data-vis:$COMMIT_SHA"
logsBucket: "gs://jalanku-bucket/logs"
